/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login_Registration;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author John Mark
 */
public class LoginTeacherForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginTeacherForm
     */
    public LoginTeacherForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1_login = new javax.swing.JButton();
        return_login = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        teacher_fname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        teacher_lname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        teacher_gender = new javax.swing.JComboBox<>();
        teacher_address = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        teacher_username = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        teacher_email = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        teacher_cpassword = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        teacher_password = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        teacher_securityq = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        teacher_securityans = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        department = new javax.swing.JComboBox<>();
        subject = new javax.swing.JComboBox<>();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(517, 652));
        jPanel1.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Teacher Registration");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1_login.setBackground(new java.awt.Color(255, 51, 51));
        jButton1_login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1_login.setText("Register");
        jButton1_login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_loginActionPerformed(evt);
            }
        });

        return_login.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        return_login.setText("Already has an account? Login here.");
        return_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        return_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                return_loginMouseClicked(evt);
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(517, 652));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Teacher Information");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel2.setText("First Name:");

        teacher_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacher_fnameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel4.setText("Last name:");

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel5.setText("Address:");

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel6.setText("Gender:");

        teacher_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel8.setText("Subject:");

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel9.setText("Department:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Account Information");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel12.setText("Username:");

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel13.setText("Email:");

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel14.setText("Password:");

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel15.setText("Confirm Password:");

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel16.setText("Security Question:");

        teacher_securityq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Where is your Birthplace?", "What primary School did you attend?", "What is the name of your brother/sister?", "Your favorite movie?", "Your favorite food?" }));

        jLabel17.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel17.setText("Security Answer:");

        jLabel18.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel18.setText("Note:");

        jLabel19.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel19.setText("Please check your information before clicking the register button.");

        department.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Kagawaran ng Filipino", "Department of English", "Department of Mathematics", "Department of Science", "Araling Panlipunan Department", "Department of Social and Behavioral Sciences", "Department of Music & Arts", "Department of Human Kinetics and Health Education", "Department of Economics" }));
        department.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                departmentItemStateChanged(evt);
            }
        });
        department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentActionPerformed(evt);
            }
        });

        subject.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select" }));
        subject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(teacher_username, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(teacher_fname)
                                    .addComponent(jLabel5)
                                    .addComponent(teacher_address)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel12)
                                    .addComponent(teacher_password)
                                    .addComponent(teacher_securityq, 0, 220, Short.MAX_VALUE))
                                .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addComponent(jLabel6)
                                .addComponent(teacher_lname, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(teacher_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)
                                .addComponent(teacher_cpassword, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel17)
                                .addComponent(teacher_securityans, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(teacher_email, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel13)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacher_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacher_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacher_address, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacher_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subject, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(department, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacher_username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacher_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacher_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacher_cpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teacher_securityq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacher_securityans, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(0, 0, 0)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jButton1_login, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(return_login))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1_login, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(return_login, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_loginActionPerformed
        // TODO add your handling code here:
        String teacherfname = teacher_fname.getText();
        String teacherlname = teacher_lname.getText();
        String teacheraddress = teacher_address.getText();
        String teachergender = teacher_gender.getSelectedItem().toString();
        String teacherdept = department.getSelectedItem().toString();
        String teachersubject = subject.getSelectedItem().toString();
        String teacherusername = teacher_username.getText();
        String teacheremail = teacher_email.getText();
        String teacherpassword = String.valueOf(teacher_password.getPassword());
        String teachercpassword = String.valueOf(teacher_cpassword.getPassword());
        String teachersecuq = teacher_securityq.getSelectedItem().toString();
        String teachersecuans = teacher_securityans.getText();
        String usertype = "Teacher";
        
        //Field requirements for registration
        if (teacherfname.equals("")){
            JOptionPane.showMessageDialog(null, "Input First Name!");
        }
        else if (teacheraddress.equals("")){
            JOptionPane.showMessageDialog(null, "Input Last Name!");
        }
        else if (teacheraddress.equals("")){
            JOptionPane.showMessageDialog(null, "Input Address!");
        }
        else if (teachergender.equals("")){
            JOptionPane.showMessageDialog(null, "Select Gender!");
        }
        else if (teacherdept.equals("")){
            JOptionPane.showMessageDialog(null, "Select Department!");
        }
        else if (teachersubject.equals("")){
            JOptionPane.showMessageDialog(null, "Select Subject!");
        }
        else if (teacherusername.equals("")){
            JOptionPane.showMessageDialog(null, "Username is required!");
        }
        else if (teacheremail.equals("")){
            JOptionPane.showMessageDialog(null, "Input Email!");
        }
        else if (!teacherpassword.equals(teachercpassword)){
            JOptionPane.showMessageDialog(null, "Password doesn't match!");
        }
        else if (teachersecuans.equals("")){
            JOptionPane.showMessageDialog(null, "Input Security Answer!");
        }
        else{
            PreparedStatement ps;
            PreparedStatement ps2;
            String query = "INSERT INTO teacher_info(teacher_fname, teacher_lname, teacher_address, teacher_gender, subject, department)VALUES (?, ?, ?, ?, ?, ?)";
            String query2 = "INSERT INTO user_info(fname, lname, username, email, password, cpassword, security_q, security_a, user_type)VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            int status = 0;
            try{
                
                
                ps2 = MySQL_Connection.getConnection().prepareStatement(query2);
                ps2.setString(1, teacherfname);
                ps2.setString(2, teacherlname);
                ps2.setString(3, teacherusername);
                ps2.setString(4, teacheremail);
                ps2.setString(5, teacherpassword);
                ps2.setString(6, teachercpassword);
                ps2.setString(7, teachersecuq);
                ps2.setString(8, teachersecuans);
                ps2.setString(9, usertype);
               
                status = ps2.executeUpdate();
                
            }

            catch(SQLException ex){
                Logger.getLogger(LoginTeacherForm.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Username already exists! Use other usernames instead");
            }
            
            if(status > 0){
                
                try{
                ps = MySQL_Connection.getConnection().prepareStatement(query);
                ps.setString(1, teacherfname);
                ps.setString(2, teacherlname);
                ps.setString(3, teacheraddress);
                ps.setString(4, teachergender);
                ps.setString(5, teachersubject);
                ps.setString(6, teacherdept);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Registration Successful");
                } catch(SQLException ex){
                        Logger.getLogger(LoginStudentForm.class.getName()).log(Level.SEVERE, null, ex);
                 }
                
            }
        }
    }//GEN-LAST:event_jButton1_loginActionPerformed

    private void return_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_return_loginMouseClicked
        // return to login
        LoginLoginForm relogin = new LoginLoginForm();
        relogin.setVisible(true);
        relogin.pack();
        relogin.setLocationRelativeTo(null);
        relogin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_return_loginMouseClicked

    private void teacher_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacher_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teacher_fnameActionPerformed

    private void departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentActionPerformed
        // TODO add your handling code here:
        if(department.getSelectedItem().equals("Kagawaran ng Filipino"))
        {
            subject.removeAllItems();
            subject.addItem("Filipino");
            subject.setSelectedItem(null);
        }
        else if(department.getSelectedItem().equals("Department of English"))
        {
            subject.removeAllItems();           
            subject.addItem("English");
            subject.setSelectedItem(null);
        }
        else if(department.getSelectedItem().equals("Department of Mathematics"))
        {
            subject.removeAllItems();           
            subject.addItem("Mathematics");
            subject.setSelectedItem(null);
        }
        else if(department.getSelectedItem().equals("Department of Science"))
        {
            subject.removeAllItems();           
            subject.addItem("Science");
            subject.setSelectedItem(null);
        }
        else if(department.getSelectedItem().equals("Araling Panlipunan Department"))
        {
            subject.removeAllItems();           
            subject.addItem("Araling Panlipunan");
            subject.setSelectedItem(null);
        }
        else if(department.getSelectedItem().equals("Department of Social and Behavioral Sciences"))
        {
            subject.removeAllItems();           
            subject.addItem("Edukasyon sa Pagpapakatao (Esp)");
            subject.setSelectedItem(null);
        }
        else if(department.getSelectedItem().equals("Department of Music & Arts"))
        {
            subject.removeAllItems();           
            subject.addItem("Music & Arts");
            subject.setSelectedItem(null);
        }
        else if(department.getSelectedItem().equals("Department of Human Kinetics and Health Education"))
        {
            subject.removeAllItems();            
            subject.addItem("Physical Education");
            subject.setSelectedItem(null);
        }
        else if(department.getSelectedItem().equals("Department of Economics"))
        {
            subject.removeAllItems();
            subject.addItem("Select");
            subject.addItem("Edukasyon Pantahanan at Pangkabuhayan (EPP)");
            subject.addItem("Technology and Livelihood Education (TLE)");
            subject.setSelectedItem(null);
        }
    }//GEN-LAST:event_departmentActionPerformed

    private void departmentItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_departmentItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_departmentItemStateChanged

    private void subjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginTeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginTeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginTeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginTeacherForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginTeacherForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> department;
    private javax.swing.JButton jButton1_login;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel return_login;
    private javax.swing.JComboBox<String> subject;
    private javax.swing.JTextField teacher_address;
    private javax.swing.JPasswordField teacher_cpassword;
    private javax.swing.JTextField teacher_email;
    private javax.swing.JTextField teacher_fname;
    private javax.swing.JComboBox<String> teacher_gender;
    private javax.swing.JTextField teacher_lname;
    private javax.swing.JPasswordField teacher_password;
    private javax.swing.JTextField teacher_securityans;
    private javax.swing.JComboBox<String> teacher_securityq;
    private javax.swing.JTextField teacher_username;
    // End of variables declaration//GEN-END:variables
}
