package Login_Registration;

import java.util.Random;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class LoginStudentForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginStudentForm
     */
    public LoginStudentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        student_password2 = new javax.swing.JPasswordField();
        student_gender1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        student_fname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        student_lname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        father_name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        student_gender = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        student_address = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        mother_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        age_text = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        student_username = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        student_email = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        student_cpassword = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        student_password = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        student_securityq = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        student_securityans = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        student_gradelvl = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        student_section = new javax.swing.JComboBox<>();
        student_register = new javax.swing.JButton();
        return_login = new javax.swing.JLabel();

        student_gender1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Registration");
        jLabel1.setFocusable(false);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Student Information");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel2.setText("First name:");

        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel4.setText("Last name:");

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel5.setText("Address:");

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel6.setText("Gender:");

        student_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel7.setText("Father's Name:");

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel8.setText("Mother's Name:");

        jLabel9.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel9.setText("Age:");

        age_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_textActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel10.setText("Grade:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Account Information");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel12.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel12.setText("Username:");

        jLabel13.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel13.setText("Email:");

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel14.setText("Password:");

        jLabel15.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel15.setText("Confirm Password:");

        student_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_passwordActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel16.setText("Security Question:");

        student_securityq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Where is your Birthplace?", "What primary School did you attend?", "What is the name of your brother/sister?", "Your favorite movie?", "Your favorite food?" }));
        student_securityq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_securityqActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel17.setText("Security Answer:");

        jLabel18.setFont(new java.awt.Font("Nirmala UI", 1, 12)); // NOI18N
        jLabel18.setText("Note:");

        jLabel19.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel19.setText("Please check your information before clicking the register button.");

        student_gradelvl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9", "10" }));
        student_gradelvl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_gradelvlActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Nirmala UI", 1, 15)); // NOI18N
        jLabel20.setText("Section:");

        student_section.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Grade Level" }));
        student_section.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_sectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(student_fname, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(student_address, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(jLabel7)
                                    .addComponent(father_name, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(jLabel9)
                                    .addComponent(age_text, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                    .addComponent(jLabel12)
                                    .addComponent(student_password)
                                    .addComponent(student_securityq, 0, 1, Short.MAX_VALUE))
                                .addComponent(student_username, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mother_name, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                .addComponent(student_lname, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                .addComponent(student_cpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                .addComponent(student_securityans, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                                .addComponent(student_email)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4)
                                        .addComponent(student_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel17)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(51, 51, 51)
                                            .addComponent(jLabel20)))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(student_gradelvl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(student_section, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jLabel14)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_fname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_lname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_address, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(father_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mother_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_gradelvl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_section, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_cpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_securityq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_securityans, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(0, 0, 0)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        student_register.setBackground(new java.awt.Color(255, 51, 51));
        student_register.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        student_register.setText("Register");
        student_register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        student_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_registerActionPerformed(evt);
            }
        });

        return_login.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        return_login.setText("Already has an account? Login here.");
        return_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        return_login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                return_loginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(student_register, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(return_login))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(student_register, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(return_login, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void student_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_registerActionPerformed
     // Button to an register account

        //variable declaration for registration
        String fname = student_fname.getText();
        String lname = student_lname.getText();
        String address = student_address.getText();
        String gender = (String) student_gender.getSelectedItem();
        String father = father_name.getText();
        String mother = mother_name.getText();
        String age = age_text.getText();
        String gradelvl = student_gradelvl.getSelectedItem().toString();
        String section = student_section.getSelectedItem().toString();
        String username = student_username.getText();
        String email = student_email.getText();
        String password = String.valueOf(student_password.getPassword());
        String cpassword = String.valueOf(student_cpassword.getPassword());
        String securityq = student_securityq.getSelectedItem().toString();
        String securitya = student_securityans.getText();
        String usertype = "Student";
        


        //Field requirements for registration
        if (fname.equals("")){
            JOptionPane.showMessageDialog(null, "Input Firstname!");
        }
        else if (lname.equals("")){
            JOptionPane.showMessageDialog(null, "Input Lastname!");
        }
        else if (address.equals("")){
            JOptionPane.showMessageDialog(null, "Input Address!");
        }
        else if (gender.equals("")){
            JOptionPane.showMessageDialog(null, "Select Gender!");
        }
        else if (father.equals("")){
            JOptionPane.showMessageDialog(null, "Input Father's Name!");
        }
        else if (mother.equals("")){
            JOptionPane.showMessageDialog(null, "Input Mother's Name!");
        }
        else if (age.equals("")){
            JOptionPane.showMessageDialog(null, "Input Age!");
        }
        else if (gradelvl.equals("")){
            JOptionPane.showMessageDialog(null, "Select Grade Level!");
        }
        else if (section.equals("")){
            JOptionPane.showMessageDialog(null, "Select Section!");
        }
        else if (username.equals("")){
            JOptionPane.showMessageDialog(null, "Username is required!");
        }
        else if (email.equals("")){
            JOptionPane.showMessageDialog(null, "Input Email!");
        }
        else if (password.equals("")){
            JOptionPane.showMessageDialog(null, "Please input password!");
        }
        else if (!password.equals(cpassword)){
            JOptionPane.showMessageDialog(null, "Password doesn't match!");
        }
        else if (securitya.equals("")){
            JOptionPane.showMessageDialog(null, "Input Security Answer!");
        }
        else{
            PreparedStatement ps;
            PreparedStatement ps2;
            String query = "INSERT INTO student_info(student_fname, student_lname, student_address, student_gender, fathers_name, mothers_name, age, gradelvl, section)VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            String query2 = "INSERT INTO user_info(fname, lname, username, email, password, cpassword, security_q, security_a, user_type)VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            
            int status2 = 0;
            

                    try{
                                                                     
                        ps2 = MySQL_Connection.getConnection().prepareStatement(query2);
                        ps2.setString(1, fname);
                        ps2.setString(2, lname);
                        ps2.setString(3, username);
                        ps2.setString(4, email);
                        ps2.setString(5, password);
                        ps2.setString(6, cpassword);
                        ps2.setString(7, securityq);
                        ps2.setString(8, securitya);
                        ps2.setString(9, usertype);

                        status2 = ps2.executeUpdate();
                                                    
                                
                    }catch(SQLException ex){
                        Logger.getLogger(LoginStudentForm.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(null, "Username already exists! Use other usernames instead");
                    }
                
                
               if(status2 > 0){
                   try{
                       ps = MySQL_Connection.getConnection().prepareStatement(query);
                        ps.setString(1, fname);
                        ps.setString(2, lname);
                        ps.setString(3, address);
                        ps.setString(4, gender);
                        ps.setString(5, father);
                        ps.setString(6, mother);
                        ps.setString(7, age);
                        ps.setString(8, gradelvl);
                        ps.setString(9, section);
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Registration Successful");
                        
                   } catch(SQLException ex){
                        Logger.getLogger(LoginStudentForm.class.getName()).log(Level.SEVERE, null, ex);
                   }
                    
                }
                

            
        }
    }//GEN-LAST:event_student_registerActionPerformed

    private void return_loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_return_loginMouseClicked
        // return to login
        LoginLoginForm relogin = new LoginLoginForm();
        relogin.setVisible(true);
        relogin.pack();
        relogin.setLocationRelativeTo(null);
        relogin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_return_loginMouseClicked

    private void student_gradelvlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_gradelvlActionPerformed
        // TODO add your handling code here:
        if(student_gradelvl.getSelectedItem().equals("7"))
        {
            student_section.removeAllItems();
            try{
                        Statement stm = MySQL_Connection.getConnection().createStatement();
                        ResultSet rs2 = stm.executeQuery("SELECT section FROM grade_section WHERE gradelvl = 7");
       
                        while(rs2.next()){
                        
                        String section = rs2.getString("section");
                        student_section.addItem(section);
                        }
                        }catch(Exception e){

                        }
            student_section.setSelectedItem(null);
        }
        if(student_gradelvl.getSelectedItem().equals("8"))
        {
            student_section.removeAllItems();
            try{
                        Statement stm = MySQL_Connection.getConnection().createStatement();
                        ResultSet rs2 = stm.executeQuery("SELECT section FROM grade_section WHERE gradelvl = 8");
       
                        while(rs2.next()){
                        
                        String section = rs2.getString("section");
                        student_section.addItem(section);
                        }
                        }catch(Exception e){

                        }
            student_section.setSelectedItem(null);
        }
        if(student_gradelvl.getSelectedItem().equals("9"))
        {
            student_section.removeAllItems();
            try{
                        Statement stm = MySQL_Connection.getConnection().createStatement();
                        ResultSet rs2 = stm.executeQuery("SELECT section FROM grade_section WHERE gradelvl = 9");
       
                        while(rs2.next()){
                        
                        String section = rs2.getString("section");
                        student_section.addItem(section);
                        }
                        }catch(Exception e){

                        }
            student_section.setSelectedItem(null);
        }
        if(student_gradelvl.getSelectedItem().equals("10"))
        {
            student_section.removeAllItems();
            try{
                        Statement stm = MySQL_Connection.getConnection().createStatement();
                        ResultSet rs2 = stm.executeQuery("SELECT section FROM grade_section WHERE gradelvl = 10");
       
                        while(rs2.next()){
                        
                        String section = rs2.getString("section");
                        student_section.addItem(section);
                        }
                        }catch(Exception e){

                        }
            student_section.setSelectedItem(null);
        }
        
    }//GEN-LAST:event_student_gradelvlActionPerformed

    private void age_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_textActionPerformed

    private void student_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_passwordActionPerformed

    private void student_securityqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_securityqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_securityqActionPerformed

    private void student_sectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_sectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_sectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginStudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age_text;
    private javax.swing.JTextField father_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField mother_name;
    private javax.swing.JLabel return_login;
    private javax.swing.JTextField student_address;
    private javax.swing.JPasswordField student_cpassword;
    private javax.swing.JTextField student_email;
    private javax.swing.JTextField student_fname;
    private javax.swing.JComboBox<String> student_gender;
    private javax.swing.JComboBox<String> student_gender1;
    private javax.swing.JComboBox<String> student_gradelvl;
    private javax.swing.JTextField student_lname;
    private javax.swing.JPasswordField student_password;
    private javax.swing.JPasswordField student_password2;
    private javax.swing.JButton student_register;
    private javax.swing.JComboBox<String> student_section;
    private javax.swing.JTextField student_securityans;
    private javax.swing.JComboBox<String> student_securityq;
    private javax.swing.JTextField student_username;
    // End of variables declaration//GEN-END:variables
}
