/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_UI;


import Login_Registration.LoginLoginForm;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import net.proteanit.sql.DbUtils;
import java.util.ArrayList;

/**
 *
 * @author NEK PC
 */
public class AdminTagStudentUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminUI
     */
    public AdminTagStudentUI() {
        initComponents();
        table_load1();
        table_load2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


        bg = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        home_btn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        teacher_btn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        student_btn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        logout_btn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tag_btn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        teachermanagement_lbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        add_grad_section = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        teachertag_combobox = new javax.swing.JComboBox<>();
        bttn_tag_students = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        grade_sectiontag_combobox = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        bttn_delete_grade_section = new javax.swing.JButton();
        Grade_level_combobox = new javax.swing.JComboBox<>();
        txtfield_section = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Tag_Student = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Grade_Section1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        display1_btn = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        display2_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(getPreferredSize());

        bg.setBackground(new java.awt.Color(51, 153, 255));
        bg.setPreferredSize(new java.awt.Dimension(1200, 720));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(0, 0, 204));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home_btn.setBackground(new java.awt.Color(0, 51, 204));
        home_btn.setToolTipText("");
        home_btn.setMinimumSize(new java.awt.Dimension(260, 0));
        home_btn.setPreferredSize(new java.awt.Dimension(261, 70));
        home_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                home_btnMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Home");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_UI/images/icons8_home_32px.png"))); // NOI18N
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout home_btnLayout = new javax.swing.GroupLayout(home_btn);
        home_btn.setLayout(home_btnLayout);
        home_btnLayout.setHorizontalGroup(
            home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_btnLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        home_btnLayout.setVerticalGroup(
            home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_btnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        sidepanel.add(home_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 300, 70));

        teacher_btn.setBackground(new java.awt.Color(0, 51, 204));
        teacher_btn.setToolTipText("");
        teacher_btn.setMinimumSize(new java.awt.Dimension(260, 0));
        teacher_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                teacher_btnMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Teacher Management");
        jLabel5.setMaximumSize(new java.awt.Dimension(51, 25));
        jLabel5.setMinimumSize(new java.awt.Dimension(51, 25));
        jLabel5.setPreferredSize(new java.awt.Dimension(51, 25));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_UI/images/icons8_management_32px.png"))); // NOI18N
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout teacher_btnLayout = new javax.swing.GroupLayout(teacher_btn);
        teacher_btn.setLayout(teacher_btnLayout);
        teacher_btnLayout.setHorizontalGroup(
            teacher_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teacher_btnLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        teacher_btnLayout.setVerticalGroup(
            teacher_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacher_btnLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(teacher_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        sidepanel.add(teacher_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 300, 70));

        student_btn.setBackground(new java.awt.Color(0, 51, 204));
        student_btn.setToolTipText("");
        student_btn.setMinimumSize(new java.awt.Dimension(260, 0));
        student_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                student_btnMousePressed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student Management");
        jLabel4.setMaximumSize(new java.awt.Dimension(51, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(51, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(51, 25));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_UI/images/icons8_student_male_26px.png"))); // NOI18N

        javax.swing.GroupLayout student_btnLayout = new javax.swing.GroupLayout(student_btn);
        student_btn.setLayout(student_btnLayout);
        student_btnLayout.setHorizontalGroup(
            student_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student_btnLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        student_btnLayout.setVerticalGroup(
            student_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student_btnLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(student_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        sidepanel.add(student_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 300, 70));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 15));
        sidepanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 122, 260, 10));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome Admin");
        sidepanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, 40));

        logout_btn.setBackground(new java.awt.Color(0, 51, 204));
        logout_btn.setToolTipText("");
        logout_btn.setMinimumSize(new java.awt.Dimension(260, 0));
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logout_btnMousePressed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Logout");
        jLabel9.setMaximumSize(new java.awt.Dimension(51, 25));
        jLabel9.setMinimumSize(new java.awt.Dimension(51, 25));
        jLabel9.setPreferredSize(new java.awt.Dimension(51, 25));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_UI/images/icons8_logout_rounded_down_32px.png"))); // NOI18N

        javax.swing.GroupLayout logout_btnLayout = new javax.swing.GroupLayout(logout_btn);
        logout_btn.setLayout(logout_btnLayout);
        logout_btnLayout.setHorizontalGroup(
            logout_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logout_btnLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logout_btnLayout.setVerticalGroup(
            logout_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logout_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logout_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 300, 50));

        tag_btn.setBackground(new java.awt.Color(0, 102, 255));
        tag_btn.setToolTipText("");
        tag_btn.setMinimumSize(new java.awt.Dimension(260, 0));
        tag_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tag_btnMousePressed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tag Student");
        jLabel11.setMaximumSize(new java.awt.Dimension(51, 25));
        jLabel11.setMinimumSize(new java.awt.Dimension(51, 25));
        jLabel11.setPreferredSize(new java.awt.Dimension(51, 25));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_UI/images/icons8_tags_32px.png"))); // NOI18N

        javax.swing.GroupLayout tag_btnLayout = new javax.swing.GroupLayout(tag_btn);
        tag_btn.setLayout(tag_btnLayout);
        tag_btnLayout.setHorizontalGroup(
            tag_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tag_btnLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        tag_btnLayout.setVerticalGroup(
            tag_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tag_btnLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(tag_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        sidepanel.add(tag_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 300, 70));

        bg.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 720));

        teachermanagement_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        teachermanagement_lbl.setForeground(new java.awt.Color(255, 255, 255));
        teachermanagement_lbl.setText("Tag Student");
        bg.add(teachermanagement_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 260, 40));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 900, 60));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel8.setText("Select Grade Level & Section:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Create Grade & Section");

        add_grad_section.setText("Confirm");
        add_grad_section.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_grad_sectionActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel14.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel14.setText("Tag Students to Teacher");

        teachertag_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Teacher" }));

        bttn_tag_students.setText("Confirm");
        bttn_tag_students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn_tag_studentsActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Teacher Name:");

        grade_sectiontag_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Grade & Section" }));

        jLabel16.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        jLabel16.setText("Grade & Section:");

        bttn_delete_grade_section.setText("Delete");
        bttn_delete_grade_section.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttn_delete_grade_sectionMouseClicked(evt);
            }
        });

        Grade_level_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9", "10" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(teachertag_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 20, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(add_grad_section)
                                .addGap(58, 58, 58)
                                .addComponent(bttn_delete_grade_section))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel13))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Grade_level_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfield_section, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(bttn_tag_students))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(grade_sectiontag_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Grade_level_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtfield_section)
                        .addGap(1, 1, 1)))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_grad_section)
                    .addComponent(bttn_delete_grade_section))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(25, 25, 25)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teachertag_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grade_sectiontag_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(bttn_tag_students)
                .addGap(26, 26, 26))
        );

        try{
            Statement stm = MySQL_Connection.getConnection().createStatement();
            ResultSet rs2 = stm.executeQuery("SELECT teacher_fname, teacher_lname FROM teacher_info");
            teachertag_combobox.removeAllItems();
            while(rs2.next()){
                String teacherfname = rs2.getString("teacher_fname");
                String teacherlname = rs2.getString("teacher_lname");
                teachertag_combobox.addItem(teacherfname + " " + teacherlname);
            }
        }catch(Exception e){

        }
        try{
            Statement stm = MySQL_Connection.getConnection().createStatement();
            ResultSet rs2 = stm.executeQuery("SELECT gradelvl, section FROM grade_section");
            grade_sectiontag_combobox.removeAllItems();
            while(rs2.next()){
                String gradelvl2 = rs2.getString("gradelvl");
                String section2 = rs2.getString("section");
                grade_sectiontag_combobox.addItem(gradelvl2 + " " + section2);
            }
        }catch(Exception e){

        }

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 360, 490));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        Tag_Student.setOpaque(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tag_Student.setViewportView(jTable1);

        Grade_Section1.setOpaque(false);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Grade_Section1.setViewportView(jTable3);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Tagged Students");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Grade & Section");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9", "10" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        display1_btn.setText("Display");
        display1_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display1_btnActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        display2_btn.setText("Display");
        display2_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display2_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tag_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(Grade_Section1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(display2_btn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(display1_btn)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(display1_btn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Grade_Section1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(display2_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tag_Student, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        try{
            Statement stm = MySQL_Connection.getConnection().createStatement();
            ResultSet rs2 = stm.executeQuery("SELECT gradelvl, section FROM grade_section");
            jComboBox1.removeAllItems();
            while(rs2.next()){
                String gradelvl2 = rs2.getString("gradelvl");
                String section2 = rs2.getString("section");
                jComboBox1.addItem(gradelvl2 + " " + section2);
            }
        }catch(Exception e){
            e.printStackTrace();
        }

        bg.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 460, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMousePressed
        // TODO add your handling code here:
        setColor(home_btn);
        resetColor(student_btn);
        resetColor(teacher_btn);
        resetColor(tag_btn);
        AdminHomeUI home = new AdminHomeUI();
        home.setVisible(true);
        home.setLocationRelativeTo(null);
        home.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_home_btnMousePressed

    private void teacher_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacher_btnMousePressed
        // TODO add your handling code here:
        setColor(teacher_btn);
        resetColor(home_btn);
        resetColor(student_btn);
        resetColor(tag_btn);
        AdminTeacherManagementUI teachermanage = new AdminTeacherManagementUI();
	teachermanage.setVisible(true);
	teachermanage.setLocationRelativeTo(null);
	teachermanage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_teacher_btnMousePressed

    private void student_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_student_btnMousePressed
        // TODO add your handling code here:
        setColor(student_btn);
        resetColor(home_btn);
        resetColor(teacher_btn);
        resetColor(tag_btn);
        AdminStudentManagementUI studentmanage= new AdminStudentManagementUI();
        studentmanage.setVisible(true);
        studentmanage.setLocationRelativeTo(null);
        studentmanage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_student_btnMousePressed

    private void logout_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMousePressed
        // Log Out
        LoginLoginForm relogin = new LoginLoginForm();
        relogin.setVisible(true);
        relogin.pack();
        relogin.setLocationRelativeTo(null);
        relogin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_logout_btnMousePressed

    private void tag_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tag_btnMousePressed
        // TODO add your handling code here:
        setColor(tag_btn);
        resetColor(home_btn);
        resetColor(teacher_btn);
        resetColor(student_btn);
        AdminTagStudentUI tag = new AdminTagStudentUI();
        tag.setVisible(true);
        tag.setLocationRelativeTo(null);
        tag.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_tag_btnMousePressed

    private void add_grad_sectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_grad_sectionActionPerformed
        // TODO add your handling code here:
          // TODO add your handling code here:
        try{
       
            String gradelvl = Grade_level_combobox.getSelectedItem().toString();
            String section = txtfield_section.getText();
            Statement stmt = MySQL_Connection.getConnection().createStatement();

            String query = "SELECT * FROM grade_section WHERE gradelvl='" + gradelvl + "' AND section='" + section + "'";
            
            ResultSet rs = stmt.executeQuery(query);
            
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Section Already Exists!");
            }
            else {
                PreparedStatement ps;
                String query2 = "INSERT INTO grade_section(gradelvl, section)VALUES (?, ?)";
                int status = 0;

                try{
                ps = MySQL_Connection.getConnection().prepareStatement(query2);
                ps.setString(1, gradelvl);
                ps.setString(2, section);

                status = ps.executeUpdate();

                if(status > 0){
                       try{
                        Statement stm = MySQL_Connection.getConnection().createStatement();
                        ResultSet rs2 = stm.executeQuery("SELECT gradelvl, section FROM grade_section");
                        grade_sectiontag_combobox.removeAllItems();
                        while(rs2.next()){
                        String gradelvl2 = rs2.getString("gradelvl");
                        String section2 = rs2.getString("section");
                        grade_sectiontag_combobox.addItem(gradelvl2 + " " + section2);
                        }
                        }catch(Exception e){

                         }
                    JOptionPane.showMessageDialog(null, "Section Added!");
                    
                }
            }

            catch(SQLException ex){
                Logger.getLogger(AdminTagStudentUI.class.getName()).log(Level.SEVERE, null, ex);
            }
                
            }
                         
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Error");
        }
        
    }//GEN-LAST:event_add_grad_sectionActionPerformed

    private void bttn_tag_studentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn_tag_studentsActionPerformed
        // TODO add your handling code here:
        String teachername = teachertag_combobox.getSelectedItem().toString();
        String gradesection = grade_sectiontag_combobox.getSelectedItem().toString();
        int teacherId=0, sectionId=0;
        PreparedStatement ps1;
        PreparedStatement ps2;
        PreparedStatement ps3;
        PreparedStatement ps6;

        String query2 = "INSERT INTO tagstudent(grade_section_id, teacher_info_user_idfk)VALUES (?, ?)";
        int status = 0;
        try{
            // replace credentials with ID records
            String sectionCheckQuery = "SELECT id FROM new_att_system.grade_section WHERE CONCAT(grade_section.gradelvl, ' ', grade_section.section)=?";
            ps1 = MySQL_Connection.getConnection().prepareStatement(sectionCheckQuery);
            ps1.setString(1, gradesection);
            ResultSet rs1 = ps1.executeQuery();
            rs1.next();
            sectionId = rs1.getInt("id");

            String teacherCheckQuery = "SELECT user_idfk FROM new_att_system.teacher_info WHERE CONCAT(teacher_info.teacher_fname, ' ', teacher_info.teacher_lname ) = ?;";
            ps6 = MySQL_Connection.getConnection().prepareStatement(teacherCheckQuery);
            ps6.setString(1, teachername);
            ResultSet rs2 = ps6.executeQuery();
            rs2.next();
            teacherId = rs2.getInt("user_idfk");

            ps2 = MySQL_Connection.getConnection().prepareStatement(query2);
            ps2.setString(1, Integer.toString(sectionId));
            ps2.setString(2, Integer.toString(teacherId));
            status = ps2.executeUpdate();

            if(status > 0){
                    table_load2();
                    JOptionPane.showMessageDialog(null, "Tagging of Section Successful");
                }
        } catch(Exception e){
            e.printStackTrace();
            try {

                String query3 = "UPDATE tagstudent SET grade_section_id = '" +sectionId + "' WHERE teacher_info_user_idfk = '" + teacherId + "'";
                ps3 = MySQL_Connection.getConnection().prepareStatement(query3);
                ps3.execute();
                JOptionPane.showMessageDialog(null, "Tagging of Section Successful");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Teacher already has section assigned!");
            }
        }
    }//GEN-LAST:event_bttn_tag_studentsActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void display1_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display1_btnActionPerformed
        // TODO add your handling code here:
        if(jComboBox3.getSelectedItem().equals("7"))
        {
             PreparedStatement pst;
                ResultSet rs;
                String query = "SELECT gradelvl as 'Grade Level', section as 'Section' FROM grade_section WHERE gradelvl=7";
                try {
                pst = MySQL_Connection.getConnection().prepareStatement(query);
                rs = pst.executeQuery();

                jTable3.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
        }
        else if(jComboBox3.getSelectedItem().equals("8"))
        {
            PreparedStatement pst;
                ResultSet rs;
                String query = "SELECT gradelvl as 'Grade Level', section as 'Section' FROM grade_section WHERE gradelvl=8";
                try {
                pst = MySQL_Connection.getConnection().prepareStatement(query);
                rs = pst.executeQuery();

                jTable3.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
        }
        else if(jComboBox3.getSelectedItem().equals("9"))
        {
            PreparedStatement pst;
                ResultSet rs;
                String query = "SELECT gradelvl as 'Grade Level', section as 'Section' FROM grade_section WHERE gradelvl=9";
                try {
                pst = MySQL_Connection.getConnection().prepareStatement(query);
                rs = pst.executeQuery();

                jTable3.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
        }
        else if(jComboBox3.getSelectedItem().equals("10"))
        {
            PreparedStatement pst;
                ResultSet rs;
                String query = "SELECT gradelvl as 'Grade Level', section as 'Section' FROM grade_section WHERE gradelvl=10";
                try {
                pst = MySQL_Connection.getConnection().prepareStatement(query);
                rs = pst.executeQuery();

                jTable3.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
        }
    }//GEN-LAST:event_display1_btnActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void display2_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display2_btnActionPerformed
        // TODO add your handling code here:
        String gradesection2 = jComboBox1.getSelectedItem().toString();

        PreparedStatement pst;
        ResultSet rs;
        String query = "SELECT CONCAT(grade_section.gradelvl, ' ', grade_section.section) as 'Grade & Section', "
            + "CONCAT(teacher_info.teacher_fname, ' ', teacher_info.teacher_lname) as 'Teacher Name' "
            + "FROM grade_section INNER JOIN tagstudent ON grade_section.id = tagstudent.grade_section_id "
            + "INNER JOIN teacher_info ON teacher_info.user_idfk = tagstudent.teacher_info_user_idfk "
            + "WHERE CONCAT(grade_section.gradelvl, ' ', grade_section.section) = ? ;";

        try {
            pst = MySQL_Connection.getConnection().prepareStatement(query);
            pst.setString(1,gradesection2);
            rs = pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }//GEN-LAST:event_display2_btnActionPerformed

    private void bttn_delete_grade_sectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttn_delete_grade_sectionMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        int selectedRow = jTable3.getSelectedRow();
        String section = jTable3.getModel().getValueAt(selectedRow, 1).toString();
        String deleteRow ="DELETE FROM grade_section WHERE section='"+section+"'";
        PreparedStatement pst;
        
        try {
            pst=MySQL_Connection.getConnection().prepareStatement(deleteRow);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record has been deleted");
            table_load1();
        } catch (SQLException ex) {
            Logger.getLogger(AdminTeacherManagementUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bttn_delete_grade_sectionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminTagStudentUI().setVisible(true);
            }
        });
    }
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(0, 102, 255));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(0, 51, 204));
    }
    
    
    //For Table 1
    public void table_load1(){
        
        
        PreparedStatement pst;
                ResultSet rs;
                String query = "SELECT gradelvl as 'Grade Level', section as 'Section' FROM grade_section WHERE gradelvl=7";
                try {
                pst = MySQL_Connection.getConnection().prepareStatement(query);
                rs = pst.executeQuery();

                jTable3.setModel(DbUtils.resultSetToTableModel(rs));
                } catch (SQLException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
        
        //SET CUSTOM RENDERER TO TEAMS COLUMN
//        jTable3.getColumnModel().getColumn(0).setCellRenderer(new ButtonRenderer());;

  //SET CUSTOM EDITOR TO TEAMS COLUMN
        jTable3.getColumnModel().getColumn(0).setCellEditor(new ButtonEditor(new JTextField()));
    }
        //For Table 2
    public void table_load2(){
        
        PreparedStatement pst;
        ResultSet rs;
        String query = "SELECT CONCAT(grade_section.gradelvl, ' ', grade_section.section) as 'Grade & Section', "
            + "CONCAT(teacher_info.teacher_fname, ' ', teacher_info.teacher_lname) as 'Teacher Name' "
            + "FROM grade_section INNER JOIN tagstudent ON grade_section.id = tagstudent.grade_section_id "
            + "INNER JOIN teacher_info ON teacher_info.user_idfk = tagstudent.teacher_info_user_idfk ;";

        try {
	pst = MySQL_Connection.getConnection().prepareStatement(query);
	rs = pst.executeQuery();
			
	jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
	}
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Grade_Section1;
    private javax.swing.JComboBox<String> Grade_level_combobox;
    private javax.swing.JScrollPane Tag_Student;
    private javax.swing.JButton add_grad_section;
    private javax.swing.JPanel bg;
    private javax.swing.JButton bttn_delete_grade_section;
    private javax.swing.JButton bttn_tag_students;
    private javax.swing.JButton display1_btn;
    private javax.swing.JButton display2_btn;
    private javax.swing.JComboBox<String> grade_sectiontag_combobox;
    private javax.swing.JPanel home_btn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JPanel logout_btn;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JPanel student_btn;
    private javax.swing.JPanel tag_btn;
    private javax.swing.JPanel teacher_btn;
    private javax.swing.JLabel teachermanagement_lbl;
    private javax.swing.JComboBox<String> teachertag_combobox;
    private javax.swing.JTextField txtfield_section;
    // End of variables declaration//GEN-END:variables

    // User Defined Variables 
    private ArrayList<String> sectionLevels;
    private ArrayList<String> sectionNames;
    private ArrayList<String> teachersFirstNames;
    private ArrayList<String> teachersLastNames;
}

class ButtonRenderer extends JButton implements  TableCellRenderer
{

  //CONSTRUCTOR
  public ButtonRenderer() {
    //SET BUTTON PROPERTIES
    setOpaque(true);
  }
  @Override
  public Component getTableCellRendererComponent(JTable table, Object obj,
      boolean selected, boolean focused, int row, int col) {

    //SET PASSED OBJECT AS BUTTON TEXT
      setText((obj==null) ? "":obj.toString());

    return this;
  }

}

//BUTTON EDITOR CLASS
class ButtonEditor extends DefaultCellEditor
{
  protected JButton btn;
   private String lbl;
   private Boolean clicked;

   public ButtonEditor(JTextField txt) {
    super(txt);

    btn=new JButton();
    btn.setOpaque(true);

    //WHEN BUTTON IS CLICKED
    btn.addActionListener(new ActionListener() {

      @Override
      public void actionPerformed(ActionEvent e) {

        fireEditingStopped();
      }
    });
  }

   //OVERRIDE A COUPLE OF METHODS
   @Override
  public Component getTableCellEditorComponent(JTable table, Object obj,
      boolean selected, int row, int col) {

      //SET TEXT TO BUTTON,SET CLICKED TO TRUE,THEN RETURN THE BTN OBJECT
     lbl=(obj==null) ? "":obj.toString();
     btn.setText(lbl);
     clicked=true;
    return btn;
  }

  //IF BUTTON CELL VALUE CHNAGES,IF CLICKED THAT IS
   @Override
  public Object getCellEditorValue() {

     if(clicked)
      {
      //SHOW US SOME MESSAGE
        JOptionPane.showMessageDialog(btn, lbl+" Clicked");
      }
    //SET IT TO FALSE NOW THAT ITS CLICKED
    clicked=false;
    return new String(lbl);
  }

   @Override
  public boolean stopCellEditing() {

         //SET CLICKED TO FALSE FIRST
      clicked=false;
    return super.stopCellEditing();
  }

   @Override
  protected void fireEditingStopped() {
    // TODO Auto-generated method stub
    super.fireEditingStopped();
  }
}
