/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User_UI;

import Login_Registration.LoginLoginForm;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.proteanit.sql.DbUtils;
import javax.swing.JOptionPane;

/**
 *
 * @author NEK PC
 */
public class AdminStudentManagementUI extends javax.swing.JFrame {

    /**
     * Creates new form AdminUI
     */
    public AdminStudentManagementUI() {
        initComponents();
        table_load();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        home_btn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        teacher_btn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        student_btn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        logout_btn = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tag_btn = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        studentmanagement_lbl = new javax.swing.JLabel();
        section_lbl = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        edit_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        search_lbl1 = new javax.swing.JLabel();
        student_gradelvl = new javax.swing.JComboBox<>();
        gradelvl_lbl = new javax.swing.JLabel();
        student_section = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(getPreferredSize());

        bg.setBackground(new java.awt.Color(51, 153, 255));
        bg.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bg.setPreferredSize(new java.awt.Dimension(1200, 720));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(0, 0, 204));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home_btn.setBackground(new java.awt.Color(0, 51, 204));
        home_btn.setToolTipText("");
        home_btn.setMinimumSize(new java.awt.Dimension(260, 0));
        home_btn.setPreferredSize(new java.awt.Dimension(261, 70));
        home_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                home_btnMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Home");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_UI/images/icons8_home_32px.png"))); // NOI18N
        jLabel2.setToolTipText("");

        javax.swing.GroupLayout home_btnLayout = new javax.swing.GroupLayout(home_btn);
        home_btn.setLayout(home_btnLayout);
        home_btnLayout.setHorizontalGroup(
            home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_btnLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        home_btnLayout.setVerticalGroup(
            home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_btnLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        sidepanel.add(home_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 300, 70));

        teacher_btn.setBackground(new java.awt.Color(0, 51, 204));
        teacher_btn.setToolTipText("");
        teacher_btn.setMinimumSize(new java.awt.Dimension(260, 0));
        teacher_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                teacher_btnMousePressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Teacher Management");
        jLabel5.setMaximumSize(new java.awt.Dimension(51, 25));
        jLabel5.setMinimumSize(new java.awt.Dimension(51, 25));
        jLabel5.setPreferredSize(new java.awt.Dimension(51, 25));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_UI/images/icons8_management_32px.png"))); // NOI18N
        jLabel3.setToolTipText("");

        javax.swing.GroupLayout teacher_btnLayout = new javax.swing.GroupLayout(teacher_btn);
        teacher_btn.setLayout(teacher_btnLayout);
        teacher_btnLayout.setHorizontalGroup(
            teacher_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teacher_btnLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        teacher_btnLayout.setVerticalGroup(
            teacher_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teacher_btnLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(teacher_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        sidepanel.add(teacher_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 300, 70));

        student_btn.setBackground(new java.awt.Color(0, 102, 255));
        student_btn.setToolTipText("");
        student_btn.setMinimumSize(new java.awt.Dimension(260, 0));
        student_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                student_btnMousePressed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Student Management");
        jLabel4.setMaximumSize(new java.awt.Dimension(51, 25));
        jLabel4.setMinimumSize(new java.awt.Dimension(51, 25));
        jLabel4.setPreferredSize(new java.awt.Dimension(51, 25));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_UI/images/icons8_student_male_26px.png"))); // NOI18N

        javax.swing.GroupLayout student_btnLayout = new javax.swing.GroupLayout(student_btn);
        student_btn.setLayout(student_btnLayout);
        student_btnLayout.setHorizontalGroup(
            student_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student_btnLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        student_btnLayout.setVerticalGroup(
            student_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(student_btnLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(student_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        sidepanel.add(student_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 300, 70));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 15));
        sidepanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 122, 260, 10));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome Admin");
        sidepanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, 40));

        logout_btn.setBackground(new java.awt.Color(0, 51, 204));
        logout_btn.setToolTipText("");
        logout_btn.setMinimumSize(new java.awt.Dimension(260, 0));
        logout_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                logout_btnMousePressed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Logout");
        jLabel9.setMaximumSize(new java.awt.Dimension(51, 25));
        jLabel9.setMinimumSize(new java.awt.Dimension(51, 25));
        jLabel9.setPreferredSize(new java.awt.Dimension(51, 25));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_UI/images/icons8_logout_rounded_down_32px.png"))); // NOI18N

        javax.swing.GroupLayout logout_btnLayout = new javax.swing.GroupLayout(logout_btn);
        logout_btn.setLayout(logout_btnLayout);
        logout_btnLayout.setHorizontalGroup(
            logout_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logout_btnLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logout_btnLayout.setVerticalGroup(
            logout_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logout_btnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logout_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        sidepanel.add(logout_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 300, 50));

        tag_btn.setBackground(new java.awt.Color(0, 51, 204));
        tag_btn.setToolTipText("");
        tag_btn.setMinimumSize(new java.awt.Dimension(260, 0));
        tag_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tag_btnMousePressed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tag Student");
        jLabel11.setMaximumSize(new java.awt.Dimension(51, 25));
        jLabel11.setMinimumSize(new java.awt.Dimension(51, 25));
        jLabel11.setPreferredSize(new java.awt.Dimension(51, 25));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/User_UI/images/icons8_tags_32px.png"))); // NOI18N

        javax.swing.GroupLayout tag_btnLayout = new javax.swing.GroupLayout(tag_btn);
        tag_btn.setLayout(tag_btnLayout);
        tag_btnLayout.setHorizontalGroup(
            tag_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tag_btnLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        tag_btnLayout.setVerticalGroup(
            tag_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tag_btnLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(tag_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        sidepanel.add(tag_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 300, 70));

        bg.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 720));

        studentmanagement_lbl.setBackground(new java.awt.Color(255, 255, 255));
        studentmanagement_lbl.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        studentmanagement_lbl.setForeground(new java.awt.Color(255, 255, 255));
        studentmanagement_lbl.setText("Student Management");
        bg.add(studentmanagement_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 260, 40));

        section_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        section_lbl.setForeground(new java.awt.Color(255, 255, 255));
        section_lbl.setText("Section:");
        bg.add(section_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 70, 30));

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        bg.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 220, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setDefaultEditor(Object.class, null);
        jScrollPane1.setViewportView(jTable1);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 820, 390));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 900, 60));

        edit_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        edit_btn.setText("Edit");
        edit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                edit_btnMouseClicked(evt);
            }
        });
        bg.add(edit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 630, 160, 40));

        delete_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        delete_btn.setText("Delete");
        bg.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, 160, 40));

        search_lbl1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        search_lbl1.setForeground(new java.awt.Color(255, 255, 255));
        search_lbl1.setText("Search:");
        bg.add(search_lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 60, 30));

        student_gradelvl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "7", "8", "9", "10" }));
        student_gradelvl.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                student_gradelvlItemStateChanged(evt);
            }
        });
        student_gradelvl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_gradelvlActionPerformed(evt);
            }
        });
        bg.add(student_gradelvl, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 80, 30));

        gradelvl_lbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gradelvl_lbl.setForeground(new java.awt.Color(255, 255, 255));
        gradelvl_lbl.setText("Grade Level:");
        bg.add(gradelvl_lbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 100, 30));

        student_section.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Grade Level" }));
        student_section.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                student_sectionItemStateChanged(evt);
            }
        });
        student_section.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_sectionActionPerformed(evt);
            }
        });
        bg.add(student_section, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 140, 120, 30));

        jButton1.setText("Display");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bg.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 140, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMousePressed
        // TODO add your handling code here:
        setColor(home_btn);
        resetColor(student_btn);
        resetColor(teacher_btn);
        resetColor(tag_btn);
        AdminHomeUI home = new AdminHomeUI();
        home.setVisible(true);
        home.setLocationRelativeTo(null);
        home.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_home_btnMousePressed

    private void teacher_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacher_btnMousePressed
        // TODO add your handling code here:
        setColor(teacher_btn);
        resetColor(home_btn);
        resetColor(student_btn);
        resetColor(tag_btn);
        AdminTeacherManagementUI teachermanage = new AdminTeacherManagementUI();
	teachermanage.setVisible(true);
	teachermanage.setLocationRelativeTo(null);
	teachermanage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_teacher_btnMousePressed

    private void student_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_student_btnMousePressed
        // TODO add your handling code here:
        setColor(student_btn);
        resetColor(home_btn);
        resetColor(teacher_btn);
        resetColor(tag_btn);
        AdminStudentManagementUI studentmanage= new AdminStudentManagementUI();
        studentmanage.setVisible(true);
        studentmanage.setLocationRelativeTo(null);
        studentmanage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_student_btnMousePressed

    private void logout_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_btnMousePressed
        // TODO add your handling code here:
        LoginLoginForm relogin = new LoginLoginForm();
        relogin.setVisible(true);
        relogin.setLocationRelativeTo(null);
        relogin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_logout_btnMousePressed

    private void tag_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tag_btnMousePressed
        // TODO add your handling code here:
        setColor(tag_btn);
        resetColor(home_btn);
        resetColor(teacher_btn);
        resetColor(student_btn);
        AdminTagStudentUI tag = new AdminTagStudentUI();
        tag.setVisible(true);
        tag.setLocationRelativeTo(null);
        tag.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_tag_btnMousePressed

    private void edit_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_btnMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
	JOptionPane.showMessageDialog(null, "No Selected Row");
	}else {
	System.out.println("selected row value:"+ selectedRow); //to show index of row in terminal
        
        String gender = jTable1.getModel().getValueAt(selectedRow, 3).toString();
        String gradelvl = jTable1.getModel().getValueAt(selectedRow, 7).toString();
        String section = jTable1.getModel().getValueAt(selectedRow, 8).toString();
        AdminEditStudent edit = new AdminEditStudent();
        edit.setVisible(true);
        edit.setLocationRelativeTo(null);
        edit.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
       
        
	edit.txt_fname.setText(model.getValueAt(selectedRow, 0).toString());
	edit.txt_lname.setText(model.getValueAt(selectedRow, 1).toString());
	edit.txt_address.setText(model.getValueAt(selectedRow, 2).toString());
        edit.gender_box.setSelectedItem(gender);
	edit.txt_fathername.setText(model.getValueAt(selectedRow, 4).toString());
        edit.txt_mothername.setText(model.getValueAt(selectedRow, 5).toString());
	edit.txt_age.setText(model.getValueAt(selectedRow, 6).toString());
        edit.student_gradelvl.setSelectedItem(gradelvl);
        edit.student_section.setSelectedItem(section);
        edit.txt_id.setText(model.getValueAt(selectedRow, 9).toString());
	
        }

        
        
    }//GEN-LAST:event_edit_btnMouseClicked

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel> (model);
        jTable1.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txt_search.getText().trim()));
    }//GEN-LAST:event_txt_searchKeyReleased

    private void student_gradelvlItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_student_gradelvlItemStateChanged
        // TODO add your handling code here:
    
    }//GEN-LAST:event_student_gradelvlItemStateChanged

    private void student_sectionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_student_sectionItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_student_sectionItemStateChanged

    private void student_gradelvlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_gradelvlActionPerformed
        // TODO add your handling code here:
        if(student_gradelvl.getSelectedItem().equals("7"))
        {
            student_section.removeAllItems();  
            try{
                        Statement stm1 = MySQL_Connection.getConnection().createStatement();
                        ResultSet rs1 = stm1.executeQuery("SELECT section FROM grade_section WHERE gradelvl=7");
                                            
                        while(rs1.next()){
                        String section2 = rs1.getString("section");
                        student_section.addItem(section2);
                        }
                        }catch(Exception e){

                         }
                 
        }
        else if(student_gradelvl.getSelectedItem().equals("8"))
        {
            student_section.removeAllItems();
            try{
                        Statement stm2 = MySQL_Connection.getConnection().createStatement();
                        ResultSet rs2 = stm2.executeQuery("SELECT section FROM grade_section WHERE gradelvl=8");
                        
                        while(rs2.next()){
                        String section2 = rs2.getString("section");
                        student_section.addItem(section2);
                        }
                        }catch(Exception e){

                         }
            
        }
        else if(student_gradelvl.getSelectedItem().equals("9"))
        {
            student_section.removeAllItems();
             try{
                        Statement stm3 = MySQL_Connection.getConnection().createStatement();
                        ResultSet rs3 = stm3.executeQuery("SELECT section FROM grade_section WHERE gradelvl=9");
                        
                        while(rs3.next()){
                        String section2 = rs3.getString("section");
                        student_section.addItem(section2);
                        }
                        }catch(Exception e){

                        }
             
        }
        else if(student_gradelvl.getSelectedItem().equals("10"))
        {
            student_section.removeAllItems();
             try{
                        Statement stm4 = MySQL_Connection.getConnection().createStatement();
                        ResultSet rs4 = stm4.executeQuery("SELECT section FROM grade_section WHERE gradelvl=10");
                        
                        while(rs4.next()){
                        String section2 = rs4.getString("section");
                        student_section.addItem(section2);
                        }
                        }catch(Exception e){

                         }
             
        }
    }//GEN-LAST:event_student_gradelvlActionPerformed

    private void student_sectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_sectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_sectionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String gradelvl2 = student_gradelvl.getSelectedItem().toString();
        String section2 = student_section.getSelectedItem().toString();
        PreparedStatement pst;
        ResultSet rs;
        String query = "SELECT student_fname as 'First Name', student_lname as 'Last Name', "
                + "student_address as 'Address', student_gender as 'Gender', "
                + "fathers_name as 'Fathers Name', mothers_name as 'Mothers Name', age as 'Age', "
                + "gradelvl as 'Grade Level', section as 'Section', user_idfk as 'ID' FROM student_info WHERE gradelvl='"+ gradelvl2 +"' AND section='" + section2 + "'";
        try {
	pst = MySQL_Connection.getConnection().prepareStatement(query);
	rs = pst.executeQuery();
			
	jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
	}
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminStudentManagementUI().setVisible(true);
            }
        });
    }
    
    void setColor(JPanel panel){
        panel.setBackground(new Color(0, 102, 255));
    }
    
    void resetColor(JPanel panel){
        panel.setBackground(new Color(0, 51, 204));
    }
    
    //For Table
    public void table_load(){
        
        PreparedStatement pst;
        ResultSet rs;
        String query = "SELECT student_fname as 'First Name', student_lname as 'Last Name', "
                + "student_address as 'Address', student_gender as 'Gender', "
                + "fathers_name as 'Fathers Name', mothers_name as 'Mothers Name', age as 'Age', "
                + "gradelvl as 'Grade Level', section as 'Section', user_idfk as 'ID' FROM student_info";
        try {
	pst = MySQL_Connection.getConnection().prepareStatement(query);
	rs = pst.executeQuery();
			
	jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
	}
    }
    
    


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton edit_btn;
    private javax.swing.JLabel gradelvl_lbl;
    private javax.swing.JPanel home_btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JTable jTable1;
    private javax.swing.JPanel logout_btn;
    private javax.swing.JLabel search_lbl1;
    private javax.swing.JLabel section_lbl;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JPanel student_btn;
    private javax.swing.JComboBox<String> student_gradelvl;
    private javax.swing.JComboBox<String> student_section;
    private javax.swing.JLabel studentmanagement_lbl;
    private javax.swing.JPanel tag_btn;
    private javax.swing.JPanel teacher_btn;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
